#!/bin/sh

# If you want to ignore code quality checks then this value can be set to true.
ignoreinsightscheck=$(git config --bool hooks.ignoreinsightscheck)

# Redirect output to stderr.
exec 1>&2

if [ "$ignoreinsightscheck" != "true" ] &&
	test(php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90) != 0
then
	cat <<\EOF
Error: Code insight check failed

If you know what you are doing you can disable this check using:

  git config hooks.ignoreinsightscheck true
EOF
	exit 1
fi
